# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['23.x']

    environment: production

    env: 
      PORT: ${{ secrets.PORT }}
      DB_URI: ${{ secrets.DB_URI }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_TEST: ${{ secrets.DB_TEST }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ORS_API_KEY: ${{ secrets.DB_URI }}      
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci #similar to npm install , except it's meant to be used in automated environments
    - run: npm run build --if-present
    - run: npm test

  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        # https://github.com/marketplace/actions/render-github-action
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: ${{ secrets.RENDER_ID }}
          # srv-xxxxxxxxxxxxxxxxxxxx
          retries: 20
          wait: 16000
          sleep: 30000

